openapi: 3.0.3
info:
  title: GopherKeeperApi
  description: GopherKeeperApi
  version: 1.0.0

servers:
  - url: /

paths:
  /health:
    post:
      description: Check health
      responses:
        200:
          description: OK

  /user/register:
    post:
      description: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterLoginReq"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterLoginResp"

  /user/login:
    post:
      description: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterLoginReq"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterLoginResp"

components:
  schemas:
    RegisterLoginReq:
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string

    RegisterLoginResp:
      required:
        - token
      properties:
        token:
          type: string
